# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(742, 443)
        self.connect_button = QtWidgets.QPushButton(Form)
        self.connect_button.setGeometry(QtCore.QRect(200, 10, 81, 31))
        self.connect_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connect_button.setObjectName("connect_button")
        self.connect_result = QtWidgets.QLabel(Form)
        self.connect_result.setGeometry(QtCore.QRect(300, 10, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.connect_result.setFont(font)
        self.connect_result.setText("")
        self.connect_result.setObjectName("connect_result")
        self.public_ip = QtWidgets.QPlainTextEdit(Form)
        self.public_ip.setGeometry(QtCore.QRect(13, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.public_ip.setFont(font)
        self.public_ip.setObjectName("public_ip")
        self.table_keyspace = QtWidgets.QTableWidget(Form)
        self.table_keyspace.setGeometry(QtCore.QRect(10, 60, 271, 192))
        self.table_keyspace.setObjectName("table_keyspace")
        self.table_keyspace.setColumnCount(0)
        self.table_keyspace.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.connect_button.setText(_translate("Form", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
